# Generated by Django 5.1.5 on 2025-01-30 08:44

import campaign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(null=True, upload_to=campaign.models.campaign_image_file_path),
        ),
    ]
