# Generated by Django 5.1.5 on 2025-05-25 22:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(
                choices=[('AC', 'Active'), ('CO', 'Completed'), ('OM', 'On Moderation'), ('RE', 'Rejected'),
                         ('EX', 'Expired')],
                db_index=True,
                default='OM',
                max_length=10
            ),
        ),
        migrations.CreateModel(
            name='CampaignDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'document',
                    models.FileField(
                        help_text='Upload a PDF document supporting this campaign.',
                        upload_to='campaign_documents/%Y/%m/%d/',
                        validators=[django.core.validators.FileExtensionValidator(['pdf'])]
                    )
                ),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                (
                    'campaign',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='campaign.campaign'
                    )
                ),
            ],
        ),
    ]
