# Generated by Django 5.1.5 on 2025-05-29 22:13

import campaign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_campaign_status_campaigndocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='deadline',
            field=models.DateField(default=campaign.models.default_deadline),
        ),
    ]
