# Generated by Django 5.1.4 on 2025-01-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('DO', 'Donor'), ('CM', 'Campaign Manager'), ('AD', 'Admin')], default='DO', max_length=20
            ),
        ),
    ]
